name: rss

on:
    schedule:
    - cron: '0/10 * * * *'
    workflow_dispatch:

jobs:
    rss:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: npm ci
              run: npm ci
              working-directory: .

            - name: fetch data
              run: node .github/actions/rss.js

            - name: Commit & Push changes
              uses: EndBug/add-and-commit@v7
              with:
                  author_name: github-actions
                  author_email: github-actions[bot]@users.noreply.github.com
                  message: 'Commit from GitHub Actions'
                  add: '["./db/*.db"]'
